/**
 * SEED DATA — Bangkok only
 * Usage: node seed-firestore.js
 */

const places = [

  // ── MORNING ───────────────────────────────────────────────

  {
    city: 'Bangkok',
    name: 'Wat Arun at Sunrise',
    description: "Set 3 alarms. The temple at dawn hits different. Worth the suffering.",
    location: { latitude: 13.7437, longitude: 100.4888 },
    time_tag: 'Morning',
    vibe_tags: ['photo', 'chill'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Wat Pho',
    description: "46-metre reclining Buddha. Serenely unbothered. Take notes.",
    location: { latitude: 13.7465, longitude: 100.4927 },
    time_tag: 'Morning',
    vibe_tags: ['photo', 'chill'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Grand Palace',
    description: "Touristy? Yes. Insanely beautiful? Also yes. Cover your shoulders or they'll send you home.",
    location: { latitude: 13.7500, longitude: 100.4913 },
    time_tag: 'Morning',
    vibe_tags: ['photo'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Or Tor Kor Market',
    description: "Best fresh market in Bangkok. Go early, buy fruit you can't name, eat it anyway.",
    location: { latitude: 13.8041, longitude: 100.5497 },
    time_tag: 'Morning',
    vibe_tags: ['foodie'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Chatuchak Weekend Market',
    description: "Everything. Literally everything. Budget 4 hours minimum and zero self-control.",
    location: { latitude: 13.7990, longitude: 100.5514 },
    time_tag: 'Morning',
    vibe_tags: ['foodie', 'chill'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Lumpini Park',
    description: "Locals doing tai chi at 6am. You won't. But it's a nice walk and the monitor lizards are huge.",
    location: { latitude: 13.7316, longitude: 100.5411 },
    time_tag: 'Morning',
    vibe_tags: ['chill'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Bang Krachao',
    description: "Bangkok's green lung, a 10-minute ferry from the chaos. Rent a bike. Get lost. Decompress.",
    location: { latitude: 13.6714, longitude: 100.5618 },
    time_tag: 'Morning',
    vibe_tags: ['chill', 'photo'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },

  // ── AFTERNOON ─────────────────────────────────────────────

  {
    city: 'Bangkok',
    name: 'Jay Fai',
    description: "Michelin star. Street food. Lady in ski goggles. The crab omelette costs a lot. You'll pay it.",
    location: { latitude: 13.7549, longitude: 100.5015 },
    time_tag: 'Afternoon',
    vibe_tags: ['foodie'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Boat Noodle Alley',
    description: "Tiny bowls. Eat 10. Still hungry. Eat 10 more. This is the way.",
    location: { latitude: 13.7622, longitude: 100.5284 },
    time_tag: 'Afternoon',
    vibe_tags: ['foodie'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Terminal 21 Food Court',
    description: "Cheapest plate lunches in any mall in Bangkok. No shame, full stomach.",
    location: { latitude: 13.7374, longitude: 100.5601 },
    time_tag: 'Afternoon',
    vibe_tags: ['foodie'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'MOCA Bangkok',
    description: "Modern art that makes you feel things. Or confused. Either reaction counts as culture.",
    location: { latitude: 13.8638, longitude: 100.5694 },
    time_tag: 'Afternoon',
    vibe_tags: ['photo', 'chill'],
    is_universal: false,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Iconsiam',
    description: "Fancy riverside mall with an indoor floating market. Air-con is free. Dignity is optional.",
    location: { latitude: 13.7234, longitude: 100.5109 },
    time_tag: 'Afternoon',
    vibe_tags: ['chill', 'photo'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },

  // ── EVENING ───────────────────────────────────────────────

  {
    city: 'Bangkok',
    name: 'Asiatique The Riverfront',
    description: "Night market on the river. Overpriced everything, undeniable vibes. Sunset is free.",
    location: { latitude: 13.7218, longitude: 100.5148 },
    time_tag: 'Evening',
    vibe_tags: ['chill', 'photo'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Mahanakhon Skywalk',
    description: "Stand on a glass floor 78 floors up and truly confront your choices.",
    location: { latitude: 13.7217, longitude: 100.5286 },
    time_tag: 'Evening',
    vibe_tags: ['photo'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Sky Bar at Lebua',
    description: "That bar from The Hangover 2. Insane views. Insane prices. Have one drink and feel very important.",
    location: { latitude: 13.7218, longitude: 100.5274 },
    time_tag: 'Evening',
    vibe_tags: ['photo', 'party'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'The Balcony Soi 4',
    description: "Open-air bar, prime people-watching, cold beer. Start here. End anywhere.",
    location: { latitude: 13.7243, longitude: 100.5295 },
    time_tag: 'Evening',
    vibe_tags: ['gay-vibe', 'chill'],
    is_universal: false,
    image_url: '',
    affiliate_link: null,
  },

  // ── NIGHT ─────────────────────────────────────────────────

  {
    city: 'Bangkok',
    name: 'Yaowarat (Chinatown)',
    description: "Street food chaos. Go hungry. Leave waddling. Bring cash, skip the diet.",
    location: { latitude: 13.7399, longitude: 100.5100 },
    time_tag: 'Night',
    vibe_tags: ['foodie'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Khao San Road',
    description: "Messy, loud, touristy, and weirdly essential. Have one bucket and leave with a story.",
    location: { latitude: 13.7590, longitude: 100.4978 },
    time_tag: 'Night',
    vibe_tags: ['party'],
    is_universal: true,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Silom Soi 4',
    description: "Bangkok's gay street. Drinks, drag, drama. The whole package on one very small soi.",
    location: { latitude: 13.7244, longitude: 100.5298 },
    time_tag: 'Night',
    vibe_tags: ['gay-vibe', 'party'],
    is_universal: false,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'DJ Station',
    description: "Three floors. Mostly men. Mostly shirtless. Zero apologies. The icon of Silom.",
    location: { latitude: 13.7247, longitude: 100.5290 },
    time_tag: 'Night',
    vibe_tags: ['gay-vibe', 'party'],
    is_universal: false,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Telephone Bar',
    description: "The OG gay bar. Vintage phone booths, cheap beer, and zero pretension.",
    location: { latitude: 13.7241, longitude: 100.5293 },
    time_tag: 'Night',
    vibe_tags: ['gay-vibe', 'chill'],
    is_universal: false,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Fake Club',
    description: "The name is ironic. The sweat is real. Very queer, very loud, no regrets.",
    location: { latitude: 13.7440, longitude: 100.5587 },
    time_tag: 'Night',
    vibe_tags: ['gay-vibe', 'party'],
    is_universal: false,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Sing Sing Theater',
    description: "The most unhinged venue in Bangkok. Dancers, dark rooms, themed chaos. Bring your weirdest self.",
    location: { latitude: 13.7386, longitude: 100.5649 },
    time_tag: 'Night',
    vibe_tags: ['party', 'photo'],
    is_universal: false,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'RCA Royal City Avenue',
    description: "Bangkok's local clubbing strip. Actual Thai people come here. That means something.",
    location: { latitude: 13.7578, longitude: 100.5697 },
    time_tag: 'Night',
    vibe_tags: ['party'],
    is_universal: false,
    image_url: '',
    affiliate_link: null,
  },
  {
    city: 'Bangkok',
    name: 'Levels Club',
    description: "Four floors of Sukhumvit nightlife. If you're still here at 3am you made the right call.",
    location: { latitude: 13.7424, longitude: 100.5609 },
    time_tag: 'Night',
    vibe_tags: ['party'],
    is_universal: false,
    image_url: '',
    affiliate_link: null,
  },

]

console.log(JSON.stringify(places, null, 2))
console.log(`\n✅ ${places.length} places ready to seed`)

module.exports = { places }
